# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket      = "airbyte-dbt-toolkit-tfstate"
    credentials = "../service_account.json"
    prefix      = "dev"
  }
}
